### PR TITLE
Remove upper case constants

### PR DESCRIPTION
**Pull request by lrhn**

### CODE REVIEW

**Comment by valotas** [comment]
Hi @lrhn , thanks for the pr but this can not make it into the master as I do not know if the changes are supported by older dart versions

**Comment by valotas** [comment]
@lrhn could you please base your pr of `dart2` branch?

**Comment by lrhn** [comment]
ACK, will do.

**Comment by lrhn** [comment]
Created new PR for this since it has a different base (and I don't know how to change the base of an existing PR): https://github.com/valotas/mustache4dart/pull/74

**Pull request closed without merging**
