### PR TITLE
Added utils_io and examples for improved Usability

### PR DESCRIPTION
**Pull request by Rodsevich**
I created a set of utilities for making easier the usage of templates.
Maybe it would be nice to upgrade the version of the package and the CHANGELOG.md, but that's not of my concern

### CODE REVIEW

**Comment by Rodsevich** [comment]
@valotas Could you consider this as a merge, please? :smiley:

**Comment by valotas** [comment]
Thanks a lot for the PR. May I ask why you think that reading files/directories with templates should be part of a template library? In my opinion it should not have to deal with reading templates from various sources.

**Comment by Rodsevich** [comment]
Just because of practical things: These are utils that could be optionally included or not. As a developer, I'd hate to include a separate _mustache4dart_utils_ package in my dependencies rather than just another import:
```import "package:mustache4dart/utils_io.dart";```

**Comment by valotas** [comment]
I strongly believe that a template library should only contain logic for templating. Should not enforce the user how to load templates. I'm afraid I have to close this.

**Pull request closed without merging**
