### PR TITLE
Support Dart 2, prepare to release 2.1.3

### PR DESCRIPTION
**Pull request by kevmoo**
Closes https://github.com/valotas/mustache4dart/pull/70

### CODE REVIEW

**Comment by kevmoo** [comment]
@valotas – you keeping track of these?

**Comment by valotas** [comment]
Hi Kevin,

Yes I am keeping track of these. For the moment dart 2 is supported but not
the browser transpilation as I am making use of the mirrors API.

I am experimenting with a source generation solution. If you feel like
helping have a look at the dart2 branch.

Cheers,
George

**Comment by kevmoo** [comment]
@valotas – awesome. Can we land this to unblock us for Dart2?

**Comment by valotas** [comment]
Hi @kevmoo,

This is a breaking change. In your PR you remove all the tests against older VMs plus current browser support.

Did you try the latest version of the library with dart2 and it doesn't work? If so what is the problem you experience.

**Comment by kevmoo** [comment]
Mirrors is 100% removed from the browser – so there is no way this will work in Dart 2 browser.

I removed all of the old SDKs because support for them is of diminishing returns. Already, must users hit our package site, etc are on v2-dev builds. I was trying to save you build times on Travis – just not worth it!

**Comment by valotas** [comment]
Can you please create a PR against `dart2` branch? I do not feel like releasing anything without browser support. For that I have to first find out a way to replace mirrors. A solution would be a new major milestone but at the moment I am on vacation with limited internet access.

**Comment by nshahan** [comment]
It would be nice to have a version that can at least be used (not in a web environment) and can version solve with the 2.0.0 SDK release. At least as a stopgap until the full release without mirrors support is completed.

**Comment by valotas** [comment]
As I said, I have at the moment limited internet access. I can address this issue sometime starting from next week. Never the less I can not just merge a PR with a failing build nor can I create a new minor version dropping support of the current stable version of dart (I do not even understand why are you asking something like that).

What I can do is create a new major. Yet again, I can not just drop support of browsers as people  again (to my surprise) rely on that.

Best thing would be to have something working on all environments (dart2, dart1 and browser). Any kind of help to that direction is more than welcome.

**Comment by valotas** [comment]
I am closing this as it is not relevant any more. [v3](https://pub.dartlang.org/packages/mustache4dart/versions/3.0.0-dev.0.0) should be running just fine on dart2. Will release a non dev version as soon as browser support is ready

**Comment by kevmoo** [comment]
ack

**Pull request closed without merging**
