### PR TITLE
A few Tweaks

### PR DESCRIPTION
**Pull request by kaendfinger**
This is a WIP to cleanup this package a bit, and to make it a bit faster if possible. It is used a lot by the community, so it should be very fast and clean code.

### CODE REVIEW

**Comment by sethladd** [comment]
What remains before it's ready to be consider for merging?

**Comment by kaendfinger** [comment]
it's ready now :)

**Comment by sethladd** [comment]
@kaendfinger can you prep this for a merge? thanks!

**Comment by kaendfinger** [comment]
Sure :)

**Pull request closed without merging**
